package com.github.ddth.queue.impl;

import com.github.ddth.commons.utils.SerializationUtils;
import com.github.ddth.queue.IQueue;
import com.github.ddth.queue.IQueueMessage;
import com.github.ddth.queue.IQueueObserver;

/**
 * Abstract queue implementation.
 * 
 * @author Thanh Nguyen <btnguyen2k@gmail.com>
 * @since 0.5.0
 */
public abstract class AbstractQueue<ID, DATA> implements IQueue<ID, DATA>, AutoCloseable {

    private String queueName;
    private IQueueObserver<ID, DATA> observer;

    /**
     * Get queue's name.
     * 
     * @return
     * @since 0.6.0
     */
    public String getQueueName() {
        return queueName;
    }

    /**
     * Set queue's name.
     * 
     * @param queueName
     * @return
     * @since 0.6.0
     */
    public AbstractQueue<ID, DATA> setQueueName(String queueName) {
        this.queueName = queueName;
        return this;
    }

    /**
     * Get queue's event observers
     * 
     * @return
     */
    public IQueueObserver<ID, DATA> getObserver() {
        return observer;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AbstractQueue<ID, DATA> setObserver(IQueueObserver<ID, DATA> observer) {
        this.observer = observer;
        return this;
    }

    /**
     * Initializing method.
     * 
     * @return
     * @throws Exception
     */
    public AbstractQueue<ID, DATA> init() throws Exception {
        if (observer != null) {
            observer.preInit(this);
        }
        try {
            return this;
        } finally {
            if (observer != null) {
                observer.postInit(this);
            }
        }
    }

    /**
     * Destroy method.
     */
    public void destroy() {
        if (observer != null) {
            observer.preDestroy(this);
        }
        if (observer != null) {
            observer.postDestroy(this);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void close() {
        destroy();
    }

    /**
     * {@inheritDoc}
     * 
     * @since 0.6.0
     */
    @Override
    public IQueueMessage<ID, DATA> createMessage() {
        return new GenericQueueMessage<>();
    }

    /**
     * {@inheritDoc}
     * 
     * @since 0.6.0
     */
    @Override
    public IQueueMessage<ID, DATA> createMessage(DATA content) {
        return GenericQueueMessage.newInstance(content);
    }

    /**
     * {@inheritDoc}
     * 
     * @since 0.6.0
     */
    @Override
    public IQueueMessage<ID, DATA> createMessage(ID id, DATA content) {
        return GenericQueueMessage.newInstance(id, content);
    }

    /**
     * Serialize a queue message to bytes.
     * 
     * @param queueMsg
     * @return
     * @since 0.7.0
     */
    protected byte[] serialize(IQueueMessage<ID, DATA> queueMsg) {
        return SerializationUtils.toByteArray(queueMsg);
    }

    /**
     * Deserialize a queue message from bytes (was generated by
     * {@link #serialize(IQueueMessage)}.
     * 
     * @param data
     * @return
     * @since 0.7.0
     */
    @SuppressWarnings("unchecked")
    protected IQueueMessage<ID, DATA> deserialize(byte[] data) {
        return deserialize(data, IQueueMessage.class);
    }

    /**
     * Deserialize a queue message from bytes (was generated by
     * {@link #serialize(IQueueMessage)}.
     * 
     * @param data
     * @param clazz
     * @return
     * @since 0.7.0
     */
    protected <T extends IQueueMessage<ID, DATA>> T deserialize(byte[] data, Class<T> clazz) {
        return SerializationUtils.fromByteArray(data, clazz);
    }
}
